services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_HREF: /sitickets/
    container_name: sitickets-frontend
    ports:
      - "8087:80"
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sitickets-backend
    ports:
      - "3032:3050"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/storage:/app/storage
    restart: always