# Etapa de compilación
FROM node:24-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

ARG BASE_HREF=/

RUN npm run build -- \
    --configuration production \
    --base-href ${BASE_HREF} \
    --deploy-url ${BASE_HREF}

# Etapa de servidor web
FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/SITickets/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]